### ISSUE TITLE
Please hire real English speaking editor

### ISSUE THREAD

**Issue by tnkmt** [bitcoincandyofficial/bitcoincandy#2]
Your website is written in Chinese English. It's not real English.

For example, `Help Bitcoin (Cash) Great Again` looks ridiculous. It should be `Help make Bitcoin (Cash) Great Again` or `Help Bitcoin (Cash) to become Great Again`, `Let's make Bitcoin (Cash) Great Again` or something (I am not native English speaker, hire real one).

**Comment by twalsh389** [comment]
I can go through the website and fix all gramatical/spelling errors. Let me know.
